trialproject/hello/urls.py
from django.urls import path
# Import views.py from directory
from . import views

urlpatterns = [
    # When someone visits default route on app, run index function from views.py
    path("", views.index, name = "index"), 

    # When someone visits /hello/brian route, runs brian function from views.py
    path("brian", views.brian, name = "brian"),

    # Name could be any name - call greet function from views.py, then pass in Name as perimeter to function
    path("<str:name>", views.greet, name="greet")
]

trialproject/newyear/urls.py
from django.urls import path
from . import views

app_name = "newyear"
urlpatterns = [
    path("", views.index, name="index"),
]

trialproject/phonebook/urls.py
from django.urls import path
from . import views

app_name = "phonebook"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

trialproject/tasks/urls.py
from django.urls import path
from . import views

app_name= "tasks"
urlpatterns = [ 
    path("", views.index, name = "index"),
    path("add", views.add, name="add")
]

trialproject/trialproject/urls.py
from django.contrib import admin
from django.urls import path, include

# Table of contents for entire Web Application
urlpatterns = [
    path('phonebook/', include("phonebook.urls")),
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls"))
]

trialproject/hello/models.py
from django.db import models

# Create your models here.

trialproject/newyear/models.py
from django.db import models

# Create your models here.

trialproject/phonebook/models.py
from django.db import models

# Create your models here.

trialproject/tasks/models.py
from django.db import models

# Create your models here.

trialproject/hello/views.py
from django.shortcuts import render

# Remember to import HttpResponse (response from server)
from django.http import HttpResponse


# Request is HTTP request from server; To seperate out HTML from Python code, render template:
def index(request):

    # Remember to name space it, in the event there's more than one index.html file
    return render(request, "hello/index.html")

def brian(request):
    return HttpResponse("Hello, Brian!")

# Takes HTTP request, as well as perimeter (Name), returns a HTTP Response with Name
def greet(request, name):

    # Takes additional third perimeter ('Name') - {} provides information, gives access to variable called 'Name' from urls.py path, value is name.capitalize()
    return render(request, "hello/greet.html", {
        "name" : name.capitalize()
    })

trialproject/newyear/views.py
from django.shortcuts import render
import datetime

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": now.month == 1 and now.day == 1
    })

trialproject/phonebook/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django import forms
from tasks.views import NewTaskForm

def index(request):
    if "name" not in request.session:
        request.session["name"] = []
    return render(request, "phonebook/index.html", {
        "name": request.session["name"]
    })

class NewContactForm(forms.Form):
    name = forms.CharField(label = "New Name")

def add(request):
    if request.method == "POST":
        form = NewContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data["name"]
            request.session["name"] += [name.capitalize()]
            return HttpResponseRedirect(reverse("phonebook:index"))
        else: 
            return render(request, "phonebook/add.html", {"form":form})
    return render(request, "phonebook/add.html", {
        "form": NewContactForm()
    })

trialproject/tasks/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse

from django.shortcuts import render

# Alternative way of generating forms - Generated by Django, takes care of all the client-side validation
from django import forms


# Create class to import new form:
# called NewTaskForm, inherits from forms.Form - within, all of the inputs you would like to get from the user
class NewTaskForm(forms.Form):

# Give class access to 'task' variable
    task = forms.CharField(label = "New Task")
# Could include "priority = forms.IntegerField(label="Priority", min_value=1, max_value=10)"

def add(request):
    if request.method == "POST":
        # request.POST contains all the data the user submitted in the form, save in 'form' variable
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            # "figure out what the url of the index url for the tasks app is, and use that url", try not to hard code the URL!, remember to import Redirect and Reverse
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, "task/add.html", {
                # Send back the existing form data that they had keyed in
                "form": form
            })
    return render(request, "tasks/add.html", {
        # Give template access to a variable called 'form', which will just be NewTaskForm()
        "form": NewTaskForm()
    })

# See add.url to plug in {{ form }}




def index(request):
    # store in user session rather than creating a global 'tasks = []' variable, Django stores data in Tables --> remember to CREATE by running "python3 manage.py migrate" in terminal
    if "tasks" not in request.session:
        request.session["tasks"] = []

    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })
# Name of variable that HTML template has access to (left), that contains value on the right

trialproject/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang=en>
    <head>
        <title>
            Hello!
        </title>
    </head>
    <body>
        # Plug in value of variable 'Name' from views.py, urls.py path
        <h1>Hello, {{name}} !</h1>
    </body>
</html>

trialproject/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang=en>
    <head>
        <title>
            Hello!
        </title>
    </head>
    <body style = "text-align: center; background-color:beige;">
        <h1>Directory:</h1>
        <a href="{% url 'tasks:index' %}">View Tasks here!</a> <br>
        <a href="{% url 'phonebook:index' %}">View Name List here!</a> <br>
        <a href="{% url 'newyear:index' %}">Check if it's New Year's here!</a> <br>
    </body>
</html>

trialproject/hello/templates/hello/layout.html
<!DOCTYPE html>
<html lang=en>
    <head>
        <title>
            Hello!
        </title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

trialproject/newyear/templates/newyear/index.html
{% load static %}
<!-- Remember to include load static -->

<!DOCTYPE html>
<html lang = "en">
    <head>
        <title>Is it New Year's?</title>
        <!-- Best practice not to insert link, but as follows: -->
        <link href="{% static 'newyear/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <!-- To include any kind of logic -->
        {% if newyear %}
            <h1>YES</h1>
        {% else %}
            <h1>NO</h1>
        {% endif %}
    </body>
</html>

trialproject/phonebook/templates/phonebook/add.html
{% extends "phonebook/layout.html" %}

{% block body%}

<form action = "{% url 'phonebook:add'%}" method = "POST">
    {% csrf_token %}

    {{ form }}
    <input type="submit">
</form>

<a href="{% url 'phonebook:index' %}">Return to Phonebook!</a>

{% endblock %}

trialproject/phonebook/templates/phonebook/index.html
{% extends "phonebook/layout.html" %}

{% block body %}
    <h1>Name List:</h1>
    
    <table>
            <tr>
                <td>Name:</td>
            </tr>
        {% for name in name %}
            <tr>
                <td>{{name}}</td><br>
            </tr>
    </table>
        {% empty %}
        No contacts.
        {% endfor %}

    <br>
    <a href="{% url 'phonebook:add' %}">Add Names!</a>
{% endblock %}

trialproject/phonebook/templates/phonebook/layout.html
<!DOCTYPE html>
<html lang = "en">
    <head>
        <title>
            My Phonebook
        </title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

trialproject/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
<h1>Tasks:</h1>

<!-- Include action to actually submit form - whenever there is submission of data that has the potential to change some state in the Application, use POST, does not include perimeters! (unlike GET) -->
<!-- Also note of CSRF (Forms Security vulnerable to request forgery) - Add CSRF token through Django Middleware! -->

    <form action = "{% url 'tasks:add'%}" method = "POST">
        {% csrf_token %}

<!-- Plug in Django-generated form from views.py here! -->
        {{ form }}
        <input type="submit">
    </form>

    <!-- Take note of name space collision! - go to urls.py for Tasks, include app_name called 'Tasks'-->
    <a href="{% url 'tasks:index' %}">Return to Tasks!</a>
{% endblock %}

trialproject/tasks/templates/tasks/index.html
<!DOCTYPE html>
<html lang = "en">
    <head>
        <title>
            Tasks
        </title>
    </head>
    <body>
        <h1>Tasks:</h1>
        <ul>
            {% for tasks in tasks %}
                <li>{{ tasks }}</li>
<!-- if empty -->
            {% empty %}
                <li>No tasks</li>
            
            {% endfor %}
        </ul>
        <!-- Instead of stating "tasks/add", instead use 'Name' - link to url called 'add' -->
        <a href="{% url 'tasks:add' %}">Add a new task!</a>
    </body>
</html>

trialproject/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang = "en">
    <head>
        <title>
            Tasks
        </title>
    </head>
    <body>
        <ul>
            <!-- 'body' is just a name, can be any name! -->
            {% block body %}
            {% endblock %}
        </ul>
    </body>
</html>